feat: add wrapper Engine
sumwatshade/enquirer-engine pull request #10
Opened 2021-04-27 21:07 UTC by jonathanlee46

Initial scaffolding for wrapper Engine that will take in JSON and options to be used as input for enquirer.

2021-04-28 17:26 UTC, jonathanlee46 commented
Need to figure out what to do with other metadata and when/where to send it, like `surveyId`.

2021-04-28 18:59 UTC, sumwatshade requested changes
Can we add at least a unit test that validates a prompt is shown? Or at least that `prompt` is executed with expected options.

2021-04-28 18:59 UTC, sumwatshade commented on src/engine/Engine.ts
> +  properties: object
Let's export these types from `src/types/Engine.ts` and include the nested properties more explicitly:

```ts
interface ISurveyPromptSettings { /* ... */ }

interface ISurveySchema {
  id: string,
  createdAt: Date,
  prompts: ISurveyPromptSettings[]
}
```

2021-04-28 18:59 UTC, sumwatshade commented on src/engine/Engine.ts
> +  constructor(options: object) {
This should have a type, `IEngineOptions`. You can also store it as `this.options` using Typescript shorthand:

```ts
	constructor(private readonly options: IEngineOptions) {}
```

2021-04-28 18:59 UTC, sumwatshade commented on src/engine/Engine.ts
> +class Engine {
```suggestion
export class EnquirerEngine {
```

2021-04-28 18:59 UTC, sumwatshade commented on src/engine/Engine.ts
> +export default Engine
```suggestion
export default EnquirerEngine
```

2021-04-28 18:59 UTC, sumwatshade commented on src/engine/Engine.ts
> +export default Engine
```suggestion
export default EnquirerEngine
```

2021-04-30 07:00 UTC, merged

2021-04-30 07:02 UTC, sumwatshade commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v0.2.0`](https://github.com/sumwatshade/enquirer-engine/releases/tag/v0.2.0) :rocket: